let bData_dummy = 
{
  "QOcachingEnabled": 0,
  "activeFavouriteCount": 2,
  "activityTabHeader": "",
  "appExtras": "",
  "businessAddress": "{\"address\":\"1122\",\"locality\":\"HSR Layout\",\"placeId\":\"ChIJfVMt45EUrjsRPFkE3PLPKkk\",\"city\":\" Bengaluru\"}",
  "businessAddressLine1": "1122",
  "businessAddressLine2": "HSR Layout",
  "businessAddressLine3": "Bengaluru",
  "businessDescription": "Long description",
  "businessHandle": "",
  "businessName": "Mahesh Newstore",
  "businessType": "One Line Descriptipn",
  "category": "",
  "categoryHeader": "",
  "consumerInviteLink": "",
  "consumerInviteText": "",
  "deliveryPricing": "",
  "favourite": false,
  "forSearch": false,
  "id": 4,
  "latitude": 12.9128825,
  "longitude": 77.6347516,
  "minAmount": 0,
  "mine": false,
  "objectId": "rKNQ10LdJO",
  "paymentEnabled": false,
  "profilePicUrl": "",
  "profileShared": false,
  "quickOrderEnabled": true,
  "quickOrderUrl": "https://razorpay.com/demo",
  "serviceAreas": "",
  "serviceRadius": 0,
  "storeTimings": "{\"Monday\": [{\"close\": 2259, \"open\": 830}], \"Tuesday\": [{\"close\": 2259, \"open\": 830}], \"Friday\": [{\"close\": 2259, \"open\": 830}], \"Wednesday\": [{\"close\": 2259, \"open\": 830}], \"Thursday\": [{\"close\": 2259, \"open\": 830}], \"Sunday\": [{\"close\": 2259, \"open\": 830}], \"Saturday\": [{\"close\": 2259, \"open\": 830}]}",
  "supplierLoggedInId": "c24017db",
  "totalFavouriteCount": 3,
  "languageType": "None",
  "userPayHidden": false
}
export default bData_dummy;